app:
    resource: '@AppBundle/Controller/DefaultController.php'
    prefix: /
    type: annotation

person_destroy:
    path:     /destroy
    defaults: { _controller: AppBundle:Default:deletePerson }
    methods:  [DELETE]

person_edit:
    path:     /edit/{id}
    defaults: { _controller: AppBundle:Default:edit }
    requirements:
        id:  \d+